# build up testing server image
# Use the official Nginx image as a parent image
FROM nginx

# Copy the custom configuration file into the container
COPY default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80
